import { useRef, useState, type MouseEvent } from 'react'
import { ArrowLeft, ArrowRight, Award, BriefcaseBusiness, Building2, Check, Clock3, Landmark, Laptop, Mail, MapPin, Menu, MessageCircle, Phone, Scale, Shield, Star, X, type LucideIcon } from 'lucide-react'
import heroImage from './assets/imagem-hero.jpeg'
import aboutImage from './assets/imagem-sobre.HEIC?url'

const whatsapp = 'https://wa.me/5521964371334?text=Olá%2C%20preciso%20de%20orientação%20jurídica%20criminal.'
const nav = [['Início','inicio'],['Sobre','sobre'],['Áreas de atuação','atuacao'],['Depoimentos','depoimentos'],['Localização','localizacao'],['Contato','contato']]
const practices: [LucideIcon,string,string][] = [
  [Shield,'Medida Protetiva','Atuação estratégica em pedidos, revisões e acompanhamento de medidas protetivas.'],
  [Scale,'Lei Maria da Penha','Orientação criteriosa em medidas protetivas e processos relacionados.'],
  [Building2,'Organização Criminosa','Defesa técnica em investigações e processos envolvendo organizações criminosas.'],
  [Laptop,'Estelionato','Atuação em investigações e processos relacionados a fraudes e estelionato.'],
  [Landmark,'Lavagem de Dinheiro','Defesa estratégica em casos de ocultação e lavagem de dinheiro.'],
  [Shield,'Crimes contra a Vida','Defesa técnica em investigações, processos e Tribunal do Júri.']
]
const testimonials = [
  ['R. M.','Fomos atendidos de madrugada, em um momento muito difícil. A condução foi firme, transparente e nos trouxe segurança desde o primeiro contato.'],
  ['Carlos A.','Profissional extremamente preparado. Explicou cada etapa com clareza e tratou o caso com a seriedade que a situação exigia.'],
  ['Fernanda S.','Atendimento humano, ágil e competente. Minha família recebeu orientação constante e uma defesa realmente estratégica.'],
  ['Nathan','Excelente profissional, conhecimento vasto na área, sempre dando retorno do andamento, disposto explicar quaisquer dúvidas que temos não só no início mas também durante todo o processo.'],
  ['Andre Figueiredo','Parabéns pelo trabalho que tem feito. Equipe maravilhosa que me atendeu super bem. Que Deus continue abençoando grandemente vocês. Obrigado por tudo que tem feito por mim. Indico e apoio.'],
  ['Ronie Cabral','100%, o atendimento é simplesmente sensacional, os profissionais muito qualificados e atenciosos, recomendo para todos os meus amigos!'],
  ['Eliane Torres','Fui muito bem assistida, já ganhei duas causas com ele, excelente profissional, acompanha os processos de perto. Parabéns!!']
]

function Logo() { return <a href="#inicio" className="flex h-full items-center whitespace-nowrap" aria-label="Paulo Ricardo - início"><span className="font-display text-lg font-semibold leading-none tracking-wide text-white min-[932px]:text-xl min-[1180px]:text-2xl">PAULO RICARDO</span></a> }

function Header(){const [open,setOpen]=useState(false);const navigateMobile=(event:MouseEvent<HTMLAnchorElement>,id:string)=>{event.preventDefault();const target=document.getElementById(id);if(!target)return;setOpen(false);window.history.pushState(null,'',`#${id}`);requestAnimationFrame(()=>requestAnimationFrame(()=>target.scrollIntoView({behavior:'smooth',block:'start'})))};return <header className="absolute inset-x-0 top-0 z-30 border-b border-white/15 text-white"><div className="container-site grid h-20 grid-cols-[1fr_auto] items-center gap-4 min-[932px]:grid-cols-[1fr_auto_1fr] min-[1180px]:flex min-[1180px]:justify-between"><div className="col-start-1 flex h-full items-center justify-self-start"><Logo/></div><nav className="hidden items-center gap-7 min-[1180px]:flex" aria-label="Navegação principal">{nav.map(([l,id])=><a key={id} href={`#${id}`} className="text-sm font-semibold text-white/75 transition hover:text-white">{l}</a>)}</nav><a href={whatsapp} target="_blank" rel="noreferrer" className="button-shape col-start-2 hidden min-h-9 items-center justify-self-center gap-2 whitespace-nowrap bg-white px-4 text-[11px] font-bold text-ink shadow-sm transition hover:bg-gray-100 min-[932px]:flex min-[1180px]:min-h-11 min-[1180px]:px-5 min-[1180px]:text-xs"><MessageCircle className="h-3.5 w-3.5 min-[1180px]:h-4 min-[1180px]:w-4"/>Falar com advogado</a><button className="button-shape col-start-2 grid h-11 w-11 place-items-center justify-self-end border border-white/25 min-[932px]:col-start-3 min-[1180px]:hidden" onClick={()=>setOpen(!open)} aria-label={open?'Fechar menu':'Abrir menu'} aria-expanded={open} aria-controls="mobile-navigation">{open?<X/>:<Menu/>}</button></div>{open&&<nav id="mobile-navigation" className="border-t border-white/15 bg-ink/95 px-5 py-3 shadow-lg min-[1180px]:hidden" aria-label="Navegação mobile">{nav.map(([l,id])=><a key={id} href={`#${id}`} onClick={event=>navigateMobile(event,id)} className="block border-b border-white/10 py-3 text-center text-sm font-medium text-white/80 transition hover:text-white last:border-b-0">{l}</a>)}</nav>}</header>}

function Hero(){return <section id="inicio" className="relative min-h-[760px] w-full overflow-hidden bg-ink pt-20 text-white lg:min-h-[800px]"><img src={heroImage} alt="Paulo Ricardo em atendimento no escritório" fetchPriority="high" className="absolute inset-0 h-full w-full object-cover object-[42%_center] sm:object-right lg:translate-x-[14%] lg:scale-110"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(15,23,42,.99)_0%,rgba(15,23,42,.93)_47%,rgba(15,23,42,.25)_100%)]"/><div className="absolute bottom-0 left-[8%] top-20 hidden w-px bg-gradient-to-b from-transparent via-white/60 to-white/10 sm:block"/><div className="container-site relative flex min-h-[680px] items-center py-16 sm:py-20 lg:min-h-[720px]"><div className="mx-auto w-full max-w-[730px] lg:max-w-none text-center sm:mx-0 sm:pl-10 sm:text-left lg:pl-16"><p className="eyebrow mb-6 !text-white/70">Defesa criminal • atendimento 24 horas</p><h1 className="hero-title font-display text-[45px] font-semibold leading-[.94] tracking-[-.035em] sm:text-7xl sm:leading-[.92] lg:text-[5rem]"><span className="lg:hidden">Advogado Criminalista com mais de <span className="font-sans font-semibold tracking-normal">11</span> anos de experiência</span><span className="hidden lg:block"><span className="block whitespace-nowrap">Advogado Criminalista</span><span className="block whitespace-nowrap">com mais de <span className="font-sans font-semibold tracking-normal">11</span> anos de experiência</span></span></h1><p className="mx-auto mt-6 max-w-xl text-[13px] leading-6 text-slate-300 sm:mx-0 sm:mt-7 sm:text-lg sm:leading-7">O Dr. Paulo Ricardo Moura Rodrigues possui duas pós-graduações em Direito Penal e Processo Penal e comanda um escritório físico com uma equipe formada por seis profissionais do Direito, atuando em diversas áreas para oferecer atendimento completo aos seus clientes.</p><div className="mt-8 flex flex-col items-center gap-4 sm:mt-9 sm:flex-row"><a href={whatsapp} target="_blank" rel="noreferrer" className="button-shape inline-flex min-h-14 items-center justify-center gap-3 bg-white px-7 text-sm font-bold text-ink shadow-sm transition hover:bg-gray-100"><MessageCircle size={19}/>Falar com advogado agora</a><span className="flex items-center justify-center gap-2 text-xs text-white/65 sm:justify-start"><span className="h-2 w-2 rounded-full bg-white"/>Atendimento imediato e confidencial</span></div></div></div></section>}

function Stats(){const data:[LucideIcon,string,string][]=[[Award,'+10','anos de experiência'],[BriefcaseBusiness,'+500','casos acompanhados'],[Clock3,'24h','atendimento emergencial'],[MapPin,'Todo Brasil','']];return <section aria-label="Indicadores de credibilidade" className="relative z-10 -mt-9 pb-20"><div className="container-site"><div className="grid gap-px overflow-hidden rounded-xl bg-gray-200 shadow-soft sm:grid-cols-2 lg:grid-cols-4">{data.map(([Icon,value,label])=><div key={value} className={`flex h-28 items-center justify-center gap-4 bg-white px-6 py-6 text-center sm:justify-start sm:text-left ${label?'':'lg:justify-center'}`}><Icon className="h-7 w-7 shrink-0 text-ink sm:h-6 sm:w-6"/><div className="min-w-0"><strong className="block whitespace-nowrap font-display text-[32px] leading-none text-ink sm:text-3xl">{value}</strong>{label&&<span className="mt-2 block whitespace-nowrap text-sm font-medium text-gray-500 sm:text-xs">{label}</span>}</div></div>)}</div></div></section>}

function About(){return <section id="sobre" className="pb-24 pt-6 lg:pb-32"><div className="container-site grid items-center gap-16 lg:grid-cols-[.9fr_1.1fr] lg:gap-24"><div className="relative mx-auto max-w-md lg:mx-0"><div className="absolute -bottom-5 -left-5 h-36 w-36 border-b border-l border-gray-300"/><img className="relative aspect-[4/5] w-full rounded-lg object-cover object-center" src={aboutImage} alt="Paulo Ricardo em retrato profissional" loading="lazy" decoding="async"/><div className="absolute -bottom-7 right-0 rounded-lg bg-ink px-7 py-5 text-white shadow-card"><b className="font-display text-3xl">OAB/RJ</b><span className="block text-[10px] tracking-[.18em] text-white/60">201.476</span></div></div><div className="text-center sm:text-left"><p className="eyebrow mb-4">Defesa com estratégia e presença</p><h2 className="section-title mx-auto max-w-2xl sm:mx-0">Experiência técnica para proteger o que é essencial.</h2><p className="mx-auto mt-6 max-w-prose leading-7 text-gray-600 sm:mx-0 sm:mt-8">Dr. Paulo Ricardo Moura Rodrigues atua exclusivamente na área criminal, reunindo sólida formação acadêmica e experiência prática em casos de alta complexidade. Cada defesa começa com escuta atenta, análise rigorosa e uma estratégia construída para as particularidades do cliente.</p><p className="mx-auto mt-4 max-w-prose leading-7 text-gray-600 sm:mx-0">Especialista em Direito Penal e Processo Penal, acompanha pessoalmente cada etapa — da delegacia aos tribunais — com comunicação clara, discrição e disponibilidade.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{['Pós-graduado em Ciências Criminais','Atuação pessoal e confidencial','Estratégia individualizada','Comunicação clara em cada etapa'].map(t=><div key={t} className="flex items-center justify-center gap-3 text-center text-sm font-semibold text-ink sm:items-start sm:justify-start sm:text-left"><span className="grid h-5 w-5 shrink-0 place-items-center rounded bg-ink text-white sm:mt-0.5"><Check size={12}/></span>{t}</div>)}</div><a href={whatsapp} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center justify-center gap-2 border-b border-ink pb-1 text-base font-bold text-ink sm:justify-start">Conheça sua linha de defesa <ArrowRight size={18}/></a></div></div></section>}

function PracticeAreas(){return <section id="atuacao" className="bg-gray-100 py-24 lg:py-32"><div className="container-site"><div className="mx-auto max-w-3xl text-center"><p className="eyebrow mb-4">Área de Atuação</p><h2 className="section-title">Defesa criminal completa, do primeiro atendimento ao tribunal.</h2></div><div className="mt-16 grid gap-4 md:grid-cols-2">{practices.map(([Icon,title,description])=><article key={title} className="group relative flex min-h-56 flex-col rounded-xl border border-gray-200 bg-white p-8 transition duration-300 hover:-translate-y-1 hover:border-gray-300 hover:shadow-card"><span className="mb-6 grid h-11 w-11 place-items-center rounded-lg border border-gray-200 text-ink transition group-hover:bg-ink group-hover:text-white"><Icon size={21}/></span><h3 className="font-display text-2xl font-semibold leading-tight text-ink">{title}</h3><p className="mt-4 max-w-prose text-base leading-7 text-gray-600">{description}</p></article>)}</div></div></section>}

function Testimonials(){const carousel=useRef<HTMLDivElement>(null);const move=(direction:number)=>carousel.current?.scrollBy({left:direction*carousel.current.clientWidth,behavior:'smooth'});return <section id="depoimentos" className="py-24 lg:py-32"><div className="container-site"><div className="text-center"><p className="eyebrow mb-4">Confiança construída na prática</p><h2 className="section-title">Quem precisou de defesa,<br/> encontrou amparo.</h2></div><div className="relative mx-auto mt-14 max-w-6xl"><button type="button" onClick={()=>move(-1)} aria-label="Depoimentos anteriores" className="absolute -left-14 top-1/2 hidden h-11 w-11 -translate-y-1/2 place-items-center rounded-lg border border-gray-200 bg-white text-ink shadow-sm transition hover:border-gray-300 lg:grid"><ArrowLeft size={18}/></button><div ref={carousel} className="flex w-full snap-x snap-mandatory gap-5 overflow-x-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{testimonials.map(([name,review])=><figure key={name} className="flex min-h-[330px] shrink-0 basis-full snap-start flex-col rounded-xl border border-gray-200 bg-white p-7 shadow-card lg:basis-[calc((100%-2.5rem)/3)]"><div className="flex gap-1 text-ink" role="img" aria-label="5 de 5 estrelas">{[1,2,3,4,5].map(n=><Star key={n} size={13} fill="currentColor" aria-hidden="true"/>)}</div><blockquote className="mt-6 font-display text-lg leading-7 text-ink">“{review}”</blockquote><figcaption className="mt-auto border-t border-gray-200 pt-5 text-xs font-bold uppercase tracking-[.15em] text-ink">{name}<span className="mt-1 block text-[10px] font-medium normal-case tracking-normal text-gray-600">Cliente verificado</span></figcaption></figure>)}</div><button type="button" onClick={()=>move(1)} aria-label="Próximos depoimentos" className="absolute -right-14 top-1/2 hidden h-11 w-11 -translate-y-1/2 place-items-center rounded-lg border border-gray-200 bg-white text-ink shadow-sm transition hover:border-gray-300 lg:grid"><ArrowRight size={18}/></button></div><div className="mx-auto mt-6 flex max-w-6xl justify-center gap-3 lg:hidden"><button type="button" onClick={()=>move(-1)} aria-label="Depoimentos anteriores" className="grid h-11 w-11 place-items-center rounded-lg border border-gray-200 bg-white text-ink shadow-sm transition hover:border-gray-300"><ArrowLeft size={18}/></button><button type="button" onClick={()=>move(1)} aria-label="Próximos depoimentos" className="grid h-11 w-11 place-items-center rounded-lg border border-gray-200 bg-white text-ink shadow-sm transition hover:border-gray-300"><ArrowRight size={18}/></button></div></div></section>}

function Location(){return <section id="localizacao" className="bg-white py-24"><div className="container-site"><div className="grid overflow-hidden rounded-xl border border-gray-200 lg:grid-cols-[1.45fr_.55fr]"><div className="relative min-h-96 w-full bg-gray-200" role="img" aria-label="Representação do mapa de localização do escritório no Centro de Niterói"><div className="absolute inset-0 opacity-55" aria-hidden="true" style={{backgroundImage:'linear-gradient(30deg,transparent 45%,#c4cbd2 46%,#c4cbd2 48%,transparent 49%),linear-gradient(-25deg,transparent 45%,#d1d6db 46%,#d1d6db 49%,transparent 50%)',backgroundSize:'90px 70px'}}/><div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2" aria-hidden="true"><span className="absolute left-1/2 top-full h-8 w-px bg-ink"/><span className="relative grid h-16 w-16 place-items-center rounded-full bg-ink text-white shadow-soft"><MapPin size={27}/></span></div><span className="absolute bottom-5 left-5 rounded-md bg-white px-4 py-2 text-[10px] font-bold uppercase tracking-wider text-gray-500" aria-hidden="true">Google Maps</span></div><div className="bg-ink p-8 text-white lg:p-10"><p className="eyebrow mb-4 !text-white/70">Escritório</p><h2 className="font-display text-4xl font-semibold">Atendimento discreto e acessível.</h2><div className="mt-8 space-y-6 text-sm"><div className="flex gap-4"><MapPin className="shrink-0 text-white" size={20}/><address className="not-italic leading-6 text-white/70"><b className="block text-white">Niterói — RJ</b>Rua Dr. Borman, 23, sala 703<br/>Centro, Niterói/RJ</address></div><div className="flex gap-4"><Clock3 className="shrink-0 text-white" size={20}/><p className="leading-6 text-white/70"><b className="block text-white">Horário comercial</b>Segunda a sexta, 9h às 18h<br/><span className="text-white">Emergências: atendimento 24h</span></p></div></div><a href="https://www.google.com/maps/search/?api=1&query=Rua%20Dr.%20Borman%2C%2023%2C%20sala%20703%2C%20Centro%2C%20Niterói%2FRJ" target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 border-b border-white/40 pb-1 text-sm font-bold">Como chegar <ArrowRight size={16}/></a></div></div></div></section>}

function FinalCta(){return <section id="contato" className="relative overflow-hidden bg-navy py-24 text-white"><div className="absolute -right-20 top-1/2 h-72 w-72 -translate-y-1/2 rounded-full border border-white/10"/><div className="absolute -right-5 top-1/2 h-48 w-48 -translate-y-1/2 rounded-full border border-gold/30"/><div className="container-site relative text-center"><p className="eyebrow mb-5 !text-white/70">Resposta imediata. Defesa presente.</p><h2 className="mx-auto max-w-3xl font-display text-5xl font-semibold leading-none sm:text-6xl">Precisa de assistência jurídica neste momento?</h2><p className="mx-auto mt-6 max-w-xl text-base leading-7 text-white/70">Converse diretamente com um advogado criminalista. Seu contato será tratado com absoluto sigilo.</p><a href={whatsapp} target="_blank" rel="noreferrer" className="button-shape mt-9 inline-flex min-h-14 items-center gap-3 bg-white px-8 text-sm font-bold text-ink shadow-sm transition hover:bg-gray-100"><MessageCircle size={19}/>Falar com advogado</a></div></section>}

function Footer(){return <footer className="border-t border-white/10 bg-[#080D18] py-16 text-white"><div className="container-site"><div className="grid gap-10 md:grid-cols-2 lg:grid-cols-4"><div><h3 className="text-xs font-bold uppercase tracking-[.16em] text-white">Paulo Ricardo</h3><p className="mt-2 text-[11px] font-medium text-white/65">Advogado Criminalista</p><p className="mt-5 max-w-xs text-xs leading-6 text-white/50">Defesa criminal estratégica, pessoal e comprometida com a preservação dos seus direitos.</p></div><div><h3 className="text-xs font-bold uppercase tracking-[.16em] text-white">Contato</h3><ul className="mt-5 space-y-3 text-sm text-white/65"><li><a href="tel:+5521964371334" className="inline-flex items-center gap-2 transition hover:text-white"><Phone size={16} aria-hidden="true"/> +55 21 96437-1334</a></li><li><a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 transition hover:text-white"><MessageCircle size={16} aria-hidden="true"/> +55 21 96437-1334</a></li><li><a href="mailto:prmr.adv@gmail.com" className="inline-flex items-center gap-2 transition hover:text-white"><Mail size={16} aria-hidden="true"/> prmr.adv@gmail.com</a></li></ul></div><div><h3 className="text-xs font-bold uppercase tracking-[.16em] text-white">Endereço</h3><address className="mt-5 text-sm not-italic leading-6 text-white/65">Rua Dr. Borman, 23, sala 703<br/>Centro, Niterói/RJ</address></div><div><h3 className="text-xs font-bold uppercase tracking-[.16em] text-white">Institucional</h3><p className="mt-5 text-sm text-white/65">Dr. Paulo Ricardo Moura Rodrigues<br/>OAB/RJ 201.476</p></div></div></div></footer>}

export default function App(){return <><a href="#main-content" className="sr-only fixed left-4 top-4 z-50 rounded-lg bg-white px-4 py-3 font-bold text-ink shadow-lg focus:not-sr-only">Pular para o conteúdo principal</a><Header/><main id="main-content" tabIndex={-1}><Hero/><Stats/><About/><PracticeAreas/><Testimonials/><Location/><FinalCta/></main><Footer/><a href={whatsapp} target="_blank" rel="noreferrer" aria-label="Falar com Paulo Ricardo pelo WhatsApp" className="fixed bottom-5 right-5 z-40 grid h-14 w-14 place-items-center rounded-full border border-white/20 bg-[#25D366] text-white shadow-[0_8px_24px_rgba(37,211,102,.3)] transition hover:scale-105 hover:shadow-[0_10px_28px_rgba(37,211,102,.38)]"><MessageCircle size={26} aria-hidden="true"/></a></>}
